# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q5KZFOju9bKvmcLeN_mh-XAcLkyjeS0i
"""

import streamlit as st
import pandas as pd
import numpy as np
import pickle

# Loading Model (Cached so it doesn't reload on every button click)
@st.cache_resource
def load_model():
    with open('XGB_model_2.pkl', 'rb') as f:
        return pickle.load(f)

# Re-creating custom functions
def wrangle_input(input_dict):
    """
    Takes raw user input dictionary, converts it to a DataFrame,
    and applies your exact preprocessing steps.
    """
    # Create DataFrame from single user input
    df = pd.DataFrame([input_dict])

    # ---wrangle function processing---
    df['tenure'] = df['tenure'].astype(float)
    df['TotalCharges'] = df['TotalCharges'].replace(' ', 0)
    df[['TotalCharges', 'MonthlyCharges']] = df[['TotalCharges', 'MonthlyCharges']].astype(float)

    # Note: df.fillna via groupby won't trigger meaningfully for a single row
    df[['TotalCharges','MonthlyCharges']] = df[['TotalCharges','MonthlyCharges']].fillna(0)

    # Convert Tenure from Month to Year
    df['tenure'] = round(df['tenure'] / 12, 2)

    # Segregating Customers by tenure
    def replace_values(column):
        if column < 1: return 'New'
        elif column <= 3: return 'Mid'
        elif column > 3: return 'Loyal'

    df['Customer Type'] = df['tenure'].apply(replace_values)

    # Handling MultipleLines (Ensuring expected categories)
    valid_lines = ['No', 'Yes']
    df['MultipleLines'] = df['MultipleLines'].apply(lambda x: x if x in valid_lines else 'N/A')

    # Payment Frequency
    if df['MonthlyCharges'].iloc[0] != 0:
        df['Payment Frequency'] = round(df['TotalCharges'] / df['MonthlyCharges'], 2)
    else:
        df['Payment Frequency'] = 0.0

    # Mapping Yes/No Columns
    map_columns = ['Partner', 'Dependents', 'PhoneService', 'PaperlessBilling']
    df[map_columns] = df[map_columns].replace({'Yes': 1, 'No': 0}).astype(int)

    # Columns to drop (dropping tenure, MonthlyCharges, etc. as per your code)
    drop_cols = ['customerID', 'MonthlyCharges', 'SeniorCitizen', 'StreamingTV', 'tenure']
    df = df.drop(drop_cols, axis=1)

    # --- One-Hot Encoding / Categorical alignment warning ---
    # Because your XGBoost model expects specific columns (including dummy variables
    # if you encoded them during training), we pass the DataFrame forward.
    # Note: If your model requires one-hot encoded columns, ensure they are handled here.

    return df

# 3. Streamlit UI Layout
st.set_page_config(page_title="Predictive Analytics App", page_icon="🔮", layout="centered")

st.title("🔮 Customer Prediction App")
st.write("Enter the customer details below to predict their status.")

st.markdown("---")

# Creating form inputs matching your wrangle function requirements
with st.form("input_form"):
    st.subheader("Customer Profile")

    # Categorical fields
    customerID = st.text_input("Customer ID", value="1234-XYZ")
    gender = st.selectbox("Gender", ["Female", "Male"])
    SeniorCitizen = st.selectbox("Senior Citizen?", [0, 1])
    Partner = st.selectbox("Has Partner?", ["Yes", "No"])
    Dependents = st.selectbox("Has Dependents?", ["Yes", "No"])

    st.subheader("Services & Billing")
    PhoneService = st.selectbox("Phone Service?", ["Yes", "No"])
    MultipleLines = st.selectbox("Multiple Lines?", ["No", "Yes", "No phone service"])
    InternetService = st.selectbox("Internet Service", ["DSL", "Fiber optic", "No"])
    OnlineSecurity = st.selectbox("Online Security", ["No", "Yes", "No internet service"])
    OnlineBackup = st.selectbox("Online Backup", ["No", "Yes", "No internet service"])
    DeviceProtection = st.selectbox("Device Protection", ["No", "Yes", "No internet service"])
    TechSupport = st.selectbox("Tech Support", ["No", "Yes", "No internet service"])
    StreamingTV = st.selectbox("Streaming TV", ["No", "Yes", "No internet service"])
    StreamingMovies = st.selectbox("Streaming Movies", ["No", "Yes", "No internet service"])

    st.subheader("Contract & Financials")
    Contract = st.selectbox("Contract Type", ["Month-to-month", "One year", "Two year"])
    PaperlessBilling = st.selectbox("Paperless Billing?", ["Yes", "No"])
    PaymentMethod = st.selectbox("Payment Method", [
        "Electronic check", "Mailed check", "Bank transfer (automatic)", "Credit card (automatic)"
    ])

    tenure = st.number_input("Tenure (in months)", min_value=0, max_value=100, value=12)
    MonthlyCharges = st.number_input("Monthly Charges ($)", min_value=0.0, value=50.0)
    TotalCharges = st.number_input("Total Charges ($)", min_value=0.0, value=600.0)

    # Submit button
    submit_button = st.form_submit_button(label="🔮 Run Prediction")

# 4. Handle Prediction
if submit_button:
    # Package inputs into a dictionary matching raw CSV structure
    raw_data = {
        "customerID": customerID, "gender": gender, "SeniorCitizen": SeniorCitizen,
        "Partner": Partner, "Dependents": Dependents, "tenure": tenure,
        "PhoneService": PhoneService, "MultipleLines": MultipleLines,
        "InternetService": InternetService, "OnlineSecurity": OnlineSecurity,
        "OnlineBackup": OnlineBackup, "DeviceProtection": DeviceProtection,
        "TechSupport": TechSupport, "StreamingTV": StreamingTV,
        "StreamingMovies": StreamingMovies, "Contract": Contract,
        "PaperlessBilling": PaperlessBilling, "PaymentMethod": PaymentMethod,
        "MonthlyCharges": MonthlyCharges, "TotalCharges": TotalCharges
    }

    try:
        # Process input data
        processed_df = wrangle_input(raw_data)

        # Load model and predict
        model = load_model()

        # NOTE: If your original training data used pd.get_dummies(), you'll need
        # to ensure processed_df matches the exact column order and format of the model.
        prediction = model.predict(processed_df)

        st.markdown("---")
        st.subheader("Result:")

        # Assuming 1 = Churn / Fraud, 0 = Loyal / Legitimate
        if prediction[0] == 1:
            st.error(f"⚠️ Warning: Model predicts **Positive/High Risk (1)**")
        else:
            st.success(f"✅ Safe: Model predicts **Negative/Low Risk (0)**")

    except Exception as e:
        st.error(f"An error occurred during prediction: {e}")
        st.info("Tip: Double check that your processed features match your XGBoost model's expected input shape.")